### PR TITLE
Usergrid 831

### PR DESCRIPTION
**Pull request by GERey**
https://issues.apache.org/jira/browse/USERGRID-831

### CODE REVIEW

**Comment by snoopdave** [comment]
Shouldn't this be done for the master branch, in case we need to release 1.0.3, etc.?

**Comment by GERey** [comment]
The ticket was marked for 2.1. I can point it at master as well

**Comment by snoopdave** [comment]
I think we should merge it to master then from there to 2.1.

**Comment by GERey** [comment]
Alright, I'll close and repoint

**Pull request closed without merging**
